/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallLog {
  'duration' : bigint,
  'user' : Principal,
  'calledAt' : Time,
  'leadId' : bigint,
  'notes' : string,
  'outcome' : CallOutcome,
}
export type CallOutcome = { 'noAnswer' : null } |
  { 'callBack' : null } |
  { 'notInterested' : null } |
  { 'interested' : null };
export type LeadStage = { 'new' : null } |
  { 'application' : null } |
  { 'funded' : null } |
  { 'approval' : null } |
  { 'contacted' : null } |
  { 'qualified' : null };
export interface StatDashboard {
  'totalLeadsAssignedToCaller' : bigint,
  'totalFunded' : number,
  'totalLeads' : bigint,
  'callsToday' : bigint,
  'avgLoanAmount' : number,
  'appsSubmitted' : bigint,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'assignedTo' : Principal,
  'completed' : boolean,
  'dueTime' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ViewLead {
  'id' : bigint,
  'assignedTo' : Principal,
  'loanAmount' : number,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'stage' : LeadStage,
  'notes' : Array<string>,
  'phone' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNoteToLead' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'createLead' : ActorMethod<[string, string, string, number], bigint>,
  'createTask' : ActorMethod<[string, Time, Principal], bigint>,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllCallLogsForCaller' : ActorMethod<[], Array<CallLog>>,
  'getAllLeads' : ActorMethod<[], Array<ViewLead>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTasksForCaller' : ActorMethod<[], Array<Task>>,
  'getCallerLeads' : ActorMethod<[], Array<ViewLead>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallsForLead' : ActorMethod<[bigint], Array<CallLog>>,
  'getLead' : ActorMethod<[bigint], ViewLead>,
  'getLeadCountByStage' : ActorMethod<[LeadStage], bigint>,
  'getLeadCountForCaller' : ActorMethod<[], bigint>,
  'getLeadsByLoanAmount' : ActorMethod<[], Array<ViewLead>>,
  'getLeadsByStage' : ActorMethod<[LeadStage], Array<ViewLead>>,
  'getLeadsCreatedToday' : ActorMethod<[], Array<ViewLead>>,
  'getLeadsOrderedByCreatedAt' : ActorMethod<[], Array<ViewLead>>,
  'getOverdueTasksForCaller' : ActorMethod<[], Array<Task>>,
  'getStatsDashboard' : ActorMethod<[], StatDashboard>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logCall' : ActorMethod<[bigint, bigint, CallOutcome, string], undefined>,
  'reassignLead' : ActorMethod<[bigint, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateLead' : ActorMethod<
    [bigint, string, string, string, number, LeadStage],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];