/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CallOutcome = IDL.Variant({
  'noAnswer' : IDL.Null,
  'callBack' : IDL.Null,
  'notInterested' : IDL.Null,
  'interested' : IDL.Null,
});
export const CallLog = IDL.Record({
  'duration' : IDL.Nat,
  'user' : IDL.Principal,
  'calledAt' : Time,
  'leadId' : IDL.Nat,
  'notes' : IDL.Text,
  'outcome' : CallOutcome,
});
export const LeadStage = IDL.Variant({
  'new' : IDL.Null,
  'application' : IDL.Null,
  'funded' : IDL.Null,
  'approval' : IDL.Null,
  'contacted' : IDL.Null,
  'qualified' : IDL.Null,
});
export const ViewLead = IDL.Record({
  'id' : IDL.Nat,
  'assignedTo' : IDL.Principal,
  'loanAmount' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'stage' : LeadStage,
  'notes' : IDL.Vec(IDL.Text),
  'phone' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'assignedTo' : IDL.Principal,
  'completed' : IDL.Bool,
  'dueTime' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StatDashboard = IDL.Record({
  'totalLeadsAssignedToCaller' : IDL.Nat,
  'totalFunded' : IDL.Float64,
  'totalLeads' : IDL.Nat,
  'callsToday' : IDL.Nat,
  'avgLoanAmount' : IDL.Float64,
  'appsSubmitted' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNoteToLead' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'createLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'createTask' : IDL.Func([IDL.Text, Time, IDL.Principal], [IDL.Nat], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllCallLogsForCaller' : IDL.Func([], [IDL.Vec(CallLog)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(ViewLead)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTasksForCaller' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerLeads' : IDL.Func([], [IDL.Vec(ViewLead)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallsForLead' : IDL.Func([IDL.Nat], [IDL.Vec(CallLog)], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [ViewLead], ['query']),
  'getLeadCountByStage' : IDL.Func([LeadStage], [IDL.Nat], ['query']),
  'getLeadCountForCaller' : IDL.Func([], [IDL.Nat], ['query']),
  'getLeadsByLoanAmount' : IDL.Func([], [IDL.Vec(ViewLead)], ['query']),
  'getLeadsByStage' : IDL.Func([LeadStage], [IDL.Vec(ViewLead)], ['query']),
  'getLeadsCreatedToday' : IDL.Func([], [IDL.Vec(ViewLead)], ['query']),
  'getLeadsOrderedByCreatedAt' : IDL.Func([], [IDL.Vec(ViewLead)], ['query']),
  'getOverdueTasksForCaller' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getStatsDashboard' : IDL.Func([], [StatDashboard], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logCall' : IDL.Func([IDL.Nat, IDL.Nat, CallOutcome, IDL.Text], [], []),
  'reassignLead' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLead' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, LeadStage],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CallOutcome = IDL.Variant({
    'noAnswer' : IDL.Null,
    'callBack' : IDL.Null,
    'notInterested' : IDL.Null,
    'interested' : IDL.Null,
  });
  const CallLog = IDL.Record({
    'duration' : IDL.Nat,
    'user' : IDL.Principal,
    'calledAt' : Time,
    'leadId' : IDL.Nat,
    'notes' : IDL.Text,
    'outcome' : CallOutcome,
  });
  const LeadStage = IDL.Variant({
    'new' : IDL.Null,
    'application' : IDL.Null,
    'funded' : IDL.Null,
    'approval' : IDL.Null,
    'contacted' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const ViewLead = IDL.Record({
    'id' : IDL.Nat,
    'assignedTo' : IDL.Principal,
    'loanAmount' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'stage' : LeadStage,
    'notes' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'assignedTo' : IDL.Principal,
    'completed' : IDL.Bool,
    'dueTime' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StatDashboard = IDL.Record({
    'totalLeadsAssignedToCaller' : IDL.Nat,
    'totalFunded' : IDL.Float64,
    'totalLeads' : IDL.Nat,
    'callsToday' : IDL.Nat,
    'avgLoanAmount' : IDL.Float64,
    'appsSubmitted' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNoteToLead' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'createLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'createTask' : IDL.Func([IDL.Text, Time, IDL.Principal], [IDL.Nat], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllCallLogsForCaller' : IDL.Func([], [IDL.Vec(CallLog)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(ViewLead)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTasksForCaller' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerLeads' : IDL.Func([], [IDL.Vec(ViewLead)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallsForLead' : IDL.Func([IDL.Nat], [IDL.Vec(CallLog)], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [ViewLead], ['query']),
    'getLeadCountByStage' : IDL.Func([LeadStage], [IDL.Nat], ['query']),
    'getLeadCountForCaller' : IDL.Func([], [IDL.Nat], ['query']),
    'getLeadsByLoanAmount' : IDL.Func([], [IDL.Vec(ViewLead)], ['query']),
    'getLeadsByStage' : IDL.Func([LeadStage], [IDL.Vec(ViewLead)], ['query']),
    'getLeadsCreatedToday' : IDL.Func([], [IDL.Vec(ViewLead)], ['query']),
    'getLeadsOrderedByCreatedAt' : IDL.Func([], [IDL.Vec(ViewLead)], ['query']),
    'getOverdueTasksForCaller' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getStatsDashboard' : IDL.Func([], [StatDashboard], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logCall' : IDL.Func([IDL.Nat, IDL.Nat, CallOutcome, IDL.Text], [], []),
    'reassignLead' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLead' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, LeadStage],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };