/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface StatDashboard {
    totalLeadsAssignedToCaller: bigint;
    totalFunded: number;
    totalLeads: bigint;
    callsToday: bigint;
    avgLoanAmount: number;
    appsSubmitted: bigint;
}
export interface ViewLead {
    id: bigint;
    assignedTo: Principal;
    loanAmount: number;
    name: string;
    createdAt: Time;
    email: string;
    stage: LeadStage;
    notes: Array<string>;
    phone: string;
}
export interface Task {
    id: bigint;
    title: string;
    assignedTo: Principal;
    completed: boolean;
    dueTime: Time;
}
export interface CallLog {
    duration: bigint;
    user: Principal;
    calledAt: Time;
    leadId: bigint;
    notes: string;
    outcome: CallOutcome;
}
export interface UserProfile {
    name: string;
}
export enum CallOutcome {
    noAnswer = "noAnswer",
    callBack = "callBack",
    notInterested = "notInterested",
    interested = "interested"
}
export enum LeadStage {
    new_ = "new",
    application = "application",
    funded = "funded",
    approval = "approval",
    contacted = "contacted",
    qualified = "qualified"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNoteToLead(leadId: bigint, note: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeTask(taskId: bigint): Promise<void>;
    createLead(name: string, phone: string, email: string, loanAmount: number): Promise<bigint>;
    createTask(title: string, dueTime: Time, assignedTo: Principal): Promise<bigint>;
    deleteLead(leadId: bigint): Promise<void>;
    deleteTask(taskId: bigint): Promise<void>;
    getAllCallLogsForCaller(): Promise<Array<CallLog>>;
    getAllLeads(): Promise<Array<ViewLead>>;
    getAllTasks(): Promise<Array<Task>>;
    getAllTasksForCaller(): Promise<Array<Task>>;
    getCallerLeads(): Promise<Array<ViewLead>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCallsForLead(leadId: bigint): Promise<Array<CallLog>>;
    getLead(leadId: bigint): Promise<ViewLead>;
    getLeadCountByStage(stage: LeadStage): Promise<bigint>;
    getLeadCountForCaller(): Promise<bigint>;
    getLeadsByLoanAmount(): Promise<Array<ViewLead>>;
    getLeadsByStage(stage: LeadStage): Promise<Array<ViewLead>>;
    getLeadsCreatedToday(): Promise<Array<ViewLead>>;
    getLeadsOrderedByCreatedAt(): Promise<Array<ViewLead>>;
    getOverdueTasksForCaller(): Promise<Array<Task>>;
    getStatsDashboard(): Promise<StatDashboard>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logCall(leadId: bigint, duration: bigint, outcome: CallOutcome, notes: string): Promise<void>;
    reassignLead(leadId: bigint, newOwner: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateLead(id: bigint, name: string, phone: string, email: string, loanAmount: number, stage: LeadStage): Promise<void>;
}
import type { CallLog as _CallLog, CallOutcome as _CallOutcome, LeadStage as _LeadStage, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, ViewLead as _ViewLead } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNoteToLead(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNoteToLead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNoteToLead(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0);
            return result;
        }
    }
    async createLead(arg0: string, arg1: string, arg2: string, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTask(arg0: string, arg1: Time, arg2: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteLead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAllCallLogsForCaller(): Promise<Array<CallLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCallLogsForCaller();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCallLogsForCaller();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLeads(): Promise<Array<ViewLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeads();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return result;
        }
    }
    async getAllTasksForCaller(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasksForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasksForCaller();
            return result;
        }
    }
    async getCallerLeads(): Promise<Array<ViewLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerLeads();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerLeads();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallsForLead(arg0: bigint): Promise<Array<CallLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallsForLead(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallsForLead(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLead(arg0: bigint): Promise<ViewLead> {
        if (this.processError) {
            try {
                const result = await this.actor.getLead(arg0);
                return from_candid_ViewLead_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLead(arg0);
            return from_candid_ViewLead_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadCountByStage(arg0: LeadStage): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadCountByStage(to_candid_LeadStage_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadCountByStage(to_candid_LeadStage_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getLeadCountForCaller(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadCountForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadCountForCaller();
            return result;
        }
    }
    async getLeadsByLoanAmount(): Promise<Array<ViewLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByLoanAmount();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByLoanAmount();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsByStage(arg0: LeadStage): Promise<Array<ViewLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsByStage(to_candid_LeadStage_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsByStage(to_candid_LeadStage_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsCreatedToday(): Promise<Array<ViewLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsCreatedToday();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsCreatedToday();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadsOrderedByCreatedAt(): Promise<Array<ViewLead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadsOrderedByCreatedAt();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadsOrderedByCreatedAt();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverdueTasksForCaller(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverdueTasksForCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverdueTasksForCaller();
            return result;
        }
    }
    async getStatsDashboard(): Promise<StatDashboard> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatsDashboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatsDashboard();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logCall(arg0: bigint, arg1: bigint, arg2: CallOutcome, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logCall(arg0, arg1, to_candid_CallOutcome_n18(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logCall(arg0, arg1, to_candid_CallOutcome_n18(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async reassignLead(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reassignLead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reassignLead(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateLead(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number, arg5: LeadStage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, arg4, to_candid_LeadStage_n16(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, arg1, arg2, arg3, arg4, to_candid_LeadStage_n16(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
function from_candid_CallLog_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallLog): CallLog {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_CallOutcome_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallOutcome): CallOutcome {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStage_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStage): LeadStage {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ViewLead_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ViewLead): ViewLead {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    assignedTo: Principal;
    loanAmount: number;
    name: string;
    createdAt: _Time;
    email: string;
    stage: _LeadStage;
    notes: Array<string>;
    phone: string;
}): {
    id: bigint;
    assignedTo: Principal;
    loanAmount: number;
    name: string;
    createdAt: Time;
    email: string;
    stage: LeadStage;
    notes: Array<string>;
    phone: string;
} {
    return {
        id: value.id,
        assignedTo: value.assignedTo,
        loanAmount: value.loanAmount,
        name: value.name,
        createdAt: value.createdAt,
        email: value.email,
        stage: from_candid_LeadStage_n11(_uploadFile, _downloadFile, value.stage),
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: bigint;
    user: Principal;
    calledAt: _Time;
    leadId: bigint;
    notes: string;
    outcome: _CallOutcome;
}): {
    duration: bigint;
    user: Principal;
    calledAt: Time;
    leadId: bigint;
    notes: string;
    outcome: CallOutcome;
} {
    return {
        duration: value.duration,
        user: value.user,
        calledAt: value.calledAt,
        leadId: value.leadId,
        notes: value.notes,
        outcome: from_candid_CallOutcome_n6(_uploadFile, _downloadFile, value.outcome)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    application: null;
} | {
    funded: null;
} | {
    approval: null;
} | {
    contacted: null;
} | {
    qualified: null;
}): LeadStage {
    return "new" in value ? LeadStage.new : "application" in value ? LeadStage.application : "funded" in value ? LeadStage.funded : "approval" in value ? LeadStage.approval : "contacted" in value ? LeadStage.contacted : "qualified" in value ? LeadStage.qualified : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    noAnswer: null;
} | {
    callBack: null;
} | {
    notInterested: null;
} | {
    interested: null;
}): CallOutcome {
    return "noAnswer" in value ? CallOutcome.noAnswer : "callBack" in value ? CallOutcome.callBack : "notInterested" in value ? CallOutcome.notInterested : "interested" in value ? CallOutcome.interested : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CallLog>): Array<CallLog> {
    return value.map((x)=>from_candid_CallLog_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ViewLead>): Array<ViewLead> {
    return value.map((x)=>from_candid_ViewLead_n9(_uploadFile, _downloadFile, x));
}
function to_candid_CallOutcome_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallOutcome): _CallOutcome {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStage_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStage): _LeadStage {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStage): {
    new: null;
} | {
    application: null;
} | {
    funded: null;
} | {
    approval: null;
} | {
    contacted: null;
} | {
    qualified: null;
} {
    return value == LeadStage.new ? {
        new_: null
    } : value == LeadStage.application ? {
        application: null
    } : value == LeadStage.funded ? {
        funded: null
    } : value == LeadStage.approval ? {
        approval: null
    } : value == LeadStage.contacted ? {
        contacted: null
    } : value == LeadStage.qualified ? {
        qualified: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallOutcome): {
    noAnswer: null;
} | {
    callBack: null;
} | {
    notInterested: null;
} | {
    interested: null;
} {
    return value == CallOutcome.noAnswer ? {
        noAnswer: null
    } : value == CallOutcome.callBack ? {
        callBack: null
    } : value == CallOutcome.notInterested ? {
        notInterested: null
    } : value == CallOutcome.interested ? {
        interested: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
